file_app/urls.py
from django.urls import path
from .import views
app_name ='file_app'
urlpatterns = [
    path('', views.FileListView.as_view(), name='file_list'),
    path('upload/', views.FileUploadView.as_view(), name='upload'),
    path('download/<int:file_id>/', views.FileDownloadView.as_view() ,name='download'),
path('get_upload_progress/', views.get_upload_progress, name='get_upload_progress'),]

file_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('file_app.urls')),
]

file_app/models.py
from django.db import models

class UploadFile(models.Model):
    file = models.FileField(upload_to='uploads/')
    upload_date = models.DateField(auto_now_add=True)
    title = models.CharField(max_length=255, blank=True)
    
    def save(self, *args, **kwargs):
        if not self.title:
            self.title = self.file.name.split('/')[-1]  # Extract file name from file path
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

file_app/forms.py
from django import forms
from .models import UploadFile

class UploadFileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget = forms.TextInput(attrs={'readonly': True})  # Set title field as read-only
        self.fields['title'].help_text = "Automatically set to the filename."

    class Meta:
        model = UploadFile
        fields = ("title", 'file',)

file_app/views.py
from django.db.models import F
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, View
from django.http import FileResponse
from django.core.paginator import Paginator
from .forms import UploadFileForm
from .models import UploadFile
from django.http import JsonResponse
 
class FileListView(ListView):
    model = UploadFile
    template_name = 'file_list.html'
    context_object_name = 'files'
    paginate_by = 10  # Number of files per page
    ordering = ['upload_date']  # Default ordering (by upload date)

    def get_queryset(self):
        queryset = super().get_queryset()
        sort_by = self.request.GET.get('sort_by')
        if sort_by == 'date':
            queryset = queryset.order_by('-upload_date')  # Sort by upload date (descending)
        elif sort_by == 'file_type':
            queryset = queryset.order_by('file')  # Sort by file type
        elif sort_by == 'size':
            queryset = queryset.annotate(file_size=F('file__size')).order_by('file_size')  # Sort by file size
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = Paginator(context['files'], self.paginate_by)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['page_obj'] = page_obj
        return context


class FileDownloadView(View):
    def get(self, request, file_id):
        uploaded_file = get_object_or_404(UploadFile, pk=file_id)
        try:
            response = FileResponse(uploaded_file.file, as_attachment=True)
            return response
        except FileNotFoundError:
            return render(request, 'error.html', {'message': 'File not found.'})
        except Exception as e:
            return render(request, 'error.html', {'message': f'An error occurred: {str(e)}'})

class FileUploadView(View):
    def get(self, request):
        form = UploadFileForm()
        return render(request, 'upload_file.html', {'form': form})

    def post(self, request):
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('file_app:check_progress')
        return render(request, 'upload_file.html', {'form': form})


def get_upload_progress(request):
    if 'upload_progress' in request.session:
        progress = request.session['upload_progress']
    else:
        progress = 0
    return JsonResponse({'progress': progress})

file_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" rel="stylesheet">
  
{% block extra_css %}
{% endblock %}

        <title>{% block title %}{% endblock title %}</title>

    </head>
    <body>
      <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <header class="mb-auto">
          <div>
            <h3 class="float-md-start mb-0">etym</h3>
            <nav class="nav nav-masthead justify-content-center float-md-end">
              <a class="nav-link fw-bold py-1 px-0 active" aria-current="page" href="#">Home</a>
              <a class="nav-link fw-bold py-1 px-0" href="#">Services</a>
              <a class="nav-link fw-bold py-1 px-0" href="{% url 'website:about'%}">about</a>
            </nav>
            <span class='user'>
              {% if request.user.is_authenticated %}
              <form method='post' action="{% url 'logout' %}">
              Hello {{user.first_name|default:request.user.username}},
              {% csrf_token %}
              <input type='submit' value='Logout'>
              </form>
              {% else %}
              <a href="{% url 'login' %}">login</a>
              {% endif %}
          </span>
          </div>
        </header>


{% block content %}{% endblock content %}
<hr/>
<footer class='fixed-bottom'>
    <ul class="bg-dark nav justify-content-center">
    <li class="nav-item"> <a class="nav-link active" href="https://www.facebook.com/# ">Facebook</a> </li> 
   <li class="nav-item"> <a class="nav-link text-re" href="https://twitter.com/#">Twitter</a> </li>
    <li class="nav-item"> <a class="nav-link" href="http://www.linkedin.com/in/#">LinkedIn</a> </li> 
   </ul>

           <p class='text-centre'> <small><a href="https:wwww.phyb.co.zw">A Phyb production</a></small></p>  
   </footer>
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

{% block extra_js %}

{% endblock %}  
 </body>
</html>

file_app/templates/file_app/file_list.html
{% extends "base.html" %}
{% block title %}list of uploaded files{% endblock title %}
{% block content %}
<h2>File List<h2>
    <ul>
        {% for file in files %}
        <li>
            {{file.file.name}}
            <a href="#">: download</a>
        </li>
        {% empty %}
        <p>No files yet</p>
        {% endfor %}
    </ul>
{% endblock content %}

file_app/templates/file_list.html
{% extends "base.html" %}
{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
{% endblock %}

{% block title %}Download files{% endblock title %}

{% block content %}
<h2>File List</h2>
<div>
    <p>Sort by:
        <a href="#" class="sort" data-sort-by="date">Date</a> |
        <a href="#" class="sort" data-sort-by="file_type">File Type</a> |
        <a href="#" class="sort" data-sort-by="size">Size</a>
    </p>
</div>
<table class="table">
    <thead>
        <tr>
            <th>File Name</th>
            <th>Upload Date</th>
            <th>File Type</th>
            <th>File Size</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for file in files %}
        <tr>
            <td>{{ file.file.name }}</td>
            <td>{{ file.upload_date }}</td>
            <td>{{ file.file.name|split:"."|last }}</td>  <!-- Extract file extension -->
            <td>{{ file.file.size }}</td>
            <td><a href="{% url 'file_app:download' file.id %}">Download</a></td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="5">No files yet</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<a href="{% url 'file_app:upload' %}" class="btn btn-primary">Upload File</a>
{% endblock content %}

{% block extra_js %}
<script src="{% static 'index.js' %}"></script>
{% endblock %}

file_app/templates/upload_file.html
{% extends "base.html" %}
{% block title %}
Upload Your File
{% endblock title %}
{% block content %}
<h2>Upload File</h2>
<form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="{{ form.file.id_for_label }}">File:</label>
        {{ form.file }}
        <small class="form-text text-muted">Select a file to upload.</small>
    </div>
    <button type="submit" class="btn btn-primary">Upload</button>
</form>
{% endblock content %}